### ISSUE TITLE
[Crawling] 크롤링모듈 크롤링 데이터에 특정 키워드 포함시 오작동하는 버그

### ISSUE THREAD

**Issue by kevin0309** [kevin0309/Cowork_Project_2021#25]
- 삽입 중 에러 발생한 책
![캡처1](https://user-images.githubusercontent.com/32089450/104669286-1f8e0000-571d-11eb-8e50-3d05d18450f8.JPG)

- 출판사 부분의 작은 따옴표때문에 에러 발생한것으로 생각 됨

- 에러 메세지
```
Traceback (most recent call last):
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\kevin\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\kevin\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\kevin\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\DEV\5. workspaces\Cowork_Project_2021\source\crawling\crawl_book_data\code\crawling_module.py", line 68, in <module>
    test.get_page_crawler()
  File "d:\DEV\5. workspaces\Cowork_Project_2021\source\crawling\crawl_book_data\code\crawling_module.py", line 63, in get_page_crawler
    self.insert_book_info(c3, books)
  File "d:\DEV\5. workspaces\Cowork_Project_2021\source\crawling\crawl_book_data\code\crawling_module.py", line 43, in insert_book_info
    self.db.execute_query(sql)
  File "d:\DEV\5. workspaces\Cowork_Project_2021\source\util\db_conn_util.py", line 47, in execute_query
    cursor.execute(query)
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\DEV\env-files\Anaconda3\envs\bs4_test\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'S',timestamp(date_format('2012.07.03','%Y.%m.%d')),349,8000,69,sysdate())' at line 1")
```

**Comment by suehyun** [comment]
* python 정규 표현식
```
import re
parse = re.sub('[-=.#/?:$}]', '', text)
```

**Comment by suehyun** [comment]
* pymysql을 이용한 데이터 INSERT 코드 변경 [[참고 링크](https://stackoverrun.com/ko/q/154051)]
    -VALUES에 %s로 문자열 포맷팅
    -예시
    ```
    cursor.execute("INSERT INTO table VALUES var1, var2, var3,")
    ```
